version: "3.7"
services:
  ocr:
    image: containerpreview.azurecr.io/microsoft/cognitive-services-recognize-text:latest
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 8g
        reservations:
          cpus: 1
          memory: 4g
    environment:
      eula: accept
      billing: "${COMPUTER_VISION_ENDPOINT_URI}"
      apikey: "${COMPUTER_VISION_API_KEY}"
    ports:
      - "5101:5000"
  formrecognizer:
    image: containerpreview.azurecr.io/microsoft/cognitive-services-form-recognizer:latest
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 8g
        reservations:
          cpus: 1
          memory: 4g
    environment:
      eula: accept
      billing: "${FORM_RECOGNIZER_ENDPOINT_URI}"
      apikey: "${FORM_RECOGNIZER_API_KEY}"
      FormRecognizer__ComputerVisionApiKey: "${COMPUTER_VISION_API_KEY}"
      FormRecognizer__ComputerVisionEndpointUri: "http://ocr:5000"
      FormRecognizer__SyncProcessTaskCancelLimitInSecs: 75
    links:
      - ocr
    volumes:
      - type: bind
        source: ./output
        target: /output
      - type: bind
        source: ./input
        target: /input
    ports:
      - "5102:5000"
  labeltool:
    image: "mcr.microsoft.com/azure-cognitive-services/custom-form/labeltool"
    ports:
      - "5103:80"
    command: "eula=accept"