services:
  psitransfer:
    ports:
      - '0.0.0.0:3000:3000'
    environment:
      - PSITRANSFER_ADMIN_PASS=secret
    volumes:
      - 'data:/data'
    image: psitrax/psitransfer

volumes:
  data:
