version: '3.3'
services:
    syncthing:
        image: 'syncthing/syncthing:latest'
        ports:
            - '8384:8384'
            - '22000:22000'
        volumes:
            - "./:/var/syncthing"
